# Generated by Django 5.0 on 2023-12-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcarerecord',
            name='report',
            field=models.FileField(upload_to=''),
        ),
    ]
