# Generated by Django 5.0 on 2023-12-19 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_healthcareprovider_fees'),
        ('Records', '0002_alter_healthcarerecord_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthcareReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.FileField(upload_to='')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Records.appointment')),
                ('healthcare_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.healthcareprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.user')),
            ],
        ),
        migrations.DeleteModel(
            name='HealthcareRecord',
        ),
    ]
